[mypy]
mypy_path = backend
explicit_package_bases = true
exclude = backend/services/climate\.py

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True